version: '3'
services:
  site:
    image: starefossen/github-pages
    ports:
      - "4000:4000"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/_site"
    command: [ "jekyll", "serve", "-d", "/_site", "--watch", "--force_polling", "-H", "0.0.0.0", "-P", "4000", "--drafts" ]
